version: "3"

services:
  gitea:
    image: gitea/gitea:1.9
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - gitea_data:/data

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - $HOME/.edgerc:/var/jenkins_home/.edgerc

volumes:
  gitea_data:
  jenkins_data:
